#!/bin/bash
num1=$((RANDOM % 100000))
num2=$((RANDOM % 100000))
sqrt1=$(sqrt $num1)
sqrt2=$(sqrt $num2)
echo "The first random number generated is $num1"
echo "The square root is $sqrt1"
echo "The second random number generated is $num2"
echo "The square root is $sqrt2"
echo "The sum of their square roots is $((sqrt1 + sqrt2))"
